/**
 * @file ReflectedEntityFinder.cpp
 * @author Echo 
 * @Date 24-4-5
 * @brief 
 */

#include "ReflectedEntityFinder.h"
#include <filesystem>
#include <iostream>
using namespace std::string_literals;

// 去掉字符串两端的空格
std::string Trim(const std::string& Str, const std::string& TrimStr = " ") {
    if (Str.empty()) {
        return Str;
    }
    std::string S = Str;
    if (S.find_first_not_of(TrimStr) != std::string::npos) {
        S.erase(0, S.find_first_not_of(TrimStr));
    }
    if (S.find_last_not_of(TrimStr) != std::string::npos) {
        S.erase(S.find_last_not_of(TrimStr) + 1);
    }
    return S;
}

bool ReplaceAll(std::string& str, const std::string& from, const std::string& to) {
    size_t start_pos = str.find(from);
    if (start_pos == std::string::npos) return false;
    str.replace(start_pos, from.length(), to);
    return true;
}

bool IsSpace(std::string Str) {
    return std::ranges::all_of(Str, [](char c) { return std::isspace(c); });
}

void replaceAll(std::string& str, const std::string& from, const std::string& to) {
    if (from.empty()) return;
    size_t start_pos = 0;
    while ((start_pos = str.find(from, start_pos)) != std::string::npos) {
        str.replace(start_pos, from.length(), to);
        start_pos += to.length();   // In case 'to' contains 'from', like replacing 'x' with 'yx'
    }
}

void ReflectedEntityFinder::run(const clang::ast_matchers::MatchFinder::MatchResult& Result) {
    using namespace clang;
    mContext       = Result.Context;
    mSourceManager = Result.SourceManager;

    auto Record = Result.Nodes.getNodeAs<CXXRecordDecl>("class");
    if (Record) return FoundRecord(Record);
    auto Field = Result.Nodes.getNodeAs<FieldDecl>("field");
    if (Field) return FoundField(Field);
}

void ReflectedEntityFinder::FoundField(const clang::FieldDecl* Decl) {
    if (mEntities.empty()) return;
    mEntities.back().AddField(Decl);
}

void ReflectedEntityFinder::FoundRecord(const clang::CXXRecordDecl* Decl) {
    mOriginalFilename = mSourceManager->getFilename(Decl->getLocation()).str();
    // 获取文件名字
    if (mFileID.empty()) {
        std::filesystem::path FilePath = mOriginalFilename;
        std::string           FileID   = FilePath.filename().generic_string();
        ReplaceAll(FileID, ".", "_");
        mFileID = FileID;
    }
    // 看看这个类有没有Reflected属性
    for (auto& Attr: Decl->attrs()) {
        if (Attr->getKind() == clang::attr::Annotate) {
            auto* AnnotateAttr = static_cast<clang::AnnotateAttr*>(Attr);
            if (AnnotateAttr->getAnnotation().starts_with("Reflected")) {
                bThisFileHasReflectedEntity = true;
                bool     Valid              = false;
                uint32_t LineNumber         = mSourceManager->getSpellingLineNumber(Decl->getLocation(), &Valid) + 1;
                mEntities.emplace_back(Decl, mConfig, LineNumber, mFileID);
                break;
            }
        }
    }
    if (mOriginalFilename.ends_with(".generated.h")) {
        llvm::outs() << "Skip generated file: " << mOriginalFilename << "\n";
        exit(0);
    }
    if (!mOriginalFilename.empty() && !mGeneratedFilename.empty()) return;
    mGeneratedFilename = mOriginalFilename;
    mGeneratedFilename.replace(mGeneratedFilename.find(".h"), 2, ".generated.h");
}

void ReflectedEntityFinder::onEndOfTranslationUnit() {
    MatchCallback::onEndOfTranslationUnit();
    if (!bThisFileHasReflectedEntity) return;
    std::error_code      ec;
    llvm::raw_fd_ostream os(mGeneratedFilename, ec);
    assert(!ec && "error opening file");
    os << "// This file generated by generator, do not edit it.\n";
    os << "#ifndef GENERATED_CODE_" << mFileID << "\n";
    os << "#define GENERATED_CODE_" << mFileID << "\n";
    for (auto& Ref: mEntities) {
        Ref.Generate(mContext, os);
    }
    os << "#undef CURRENT_FILE_ID\n";
    os << "#define CURRENT_FILE_ID " << mFileID << "\n";
    os << "#endif";
}

std::string ClassEntity::GetBaseClassName() const {
    if (!mRecord->bases().empty()) {
        const clang::CXXBaseSpecifier* BaseSpecifier   = mRecord->bases_begin();
        const CXXRecordDecl*           BaseRecordDecl  = BaseSpecifier->getType()->getAsCXXRecordDecl();
        const std::string              base_class_name = BaseRecordDecl->getQualifiedNameAsString();
        return base_class_name;
    }
    return "";
}

std::string ClassEntity::GetClassName() const {
    if (mRecord) {
        return mRecord->getQualifiedNameAsString();
    }
    return "";
}

void ClassEntity::GenerateField(const clang::FieldDecl*                   Decl,
                                const std::map<std::string, std::string>& AttrMap,
                                llvm::raw_fd_ostream&                     os) const {
    std::string FieldDeclName = Decl->getNameAsString();
    std::string FieldName     = FieldDeclName;
    std::string FieldTypeName = Decl->getType().getAsString();
    if (AttrMap.find("Name") != AttrMap.end()) {
        FieldName = AttrMap.at("Name");
    }
    std::string RegisterStr = std::vformat(R"(.property("{}", &{}::{}))",
                                           std::make_format_args(FieldName, GetClassName(), FieldDeclName));
    for (const auto& [Key, Value]: AttrMap) {
        if (Key == "Name") continue;
        if (Key == "Reflected") continue;
        RegisterStr += std::vformat(R"((rttr::metadata("{}", "{}")))", std::make_format_args(Key, Value));
    }
    if (mConig.isMember("RefWrapperType")) {
        for (auto& Value: mConig["RefWrapperType"]) {
            auto WarpperStr = Value.asString();
            if (FieldTypeName.starts_with(WarpperStr)) {
                RegisterStr += std::string("(rttr::policy::prop::as_reference_wrapper)");
                break;
            }
        }
    }
    RegisterStr += " \\\n";
    os << RegisterStr;
}

void ClassEntity::Generate(const clang::ASTContext* context, llvm::raw_fd_ostream& os) const {
    std::string CodeMacroStr = std::vformat(R"(#define GENERATED_CODE_{}{} \)",
                                            std::make_format_args(mCurrentFileID, mReflDeclLineNumber));
    os << CodeMacroStr << "\n";
    std::string RegisterClassCode = std::vformat(R"(rttr::registration::class_<{}>("{}") \)",
                                                 std::make_format_args(GetClassName(), GetClassName()));
    os << RegisterClassCode << "\n";
    for (const auto& Field: mFields) {
        // 寻找annoation attr
        std::string AttrStr;
        for (const auto& attr: Field->attrs()) {
            if (attr->getKind() == clang::attr::Annotate) {
                auto* AnnotateAttr = static_cast<clang::AnnotateAttr*>(attr);
                AttrStr            = AnnotateAttr->getAnnotation();
                break;
            }
        }
        auto AttrMap = GetFieldAttributes(AttrStr);
        GenerateField(Field, AttrMap, os);
    }
    os << ";\n";
    std::string ThisClassName          = GetClassName();
    std::string ParentClassName        = GetBaseClassName();
    std::string ParentClassNameTypedef = ParentClassName.empty() ? "" : "typedef "s + ParentClassName + " Super;";
    std::string RTTREnable             = ParentClassName.empty() ? "" : "RTTR_ENABLE("s + ParentClassName + ")";
    // clang-format off
    std::string RegisterGeneratedBody = std::vformat(R"(
#define GENERATED_BODY_{}_{} \
public: \
    typedef {} ThisClass; \
    {} \
    {} \
    RTTR_REGISTRATION_FRIEND \
    REGISTRATION_IN_CLASS(CURRENT_FILE_ID, __LINE__) {{ \
        GENERATED_CODE_{}{} \
    }} \
private:)",std::make_format_args(mCurrentFileID, mReflDeclLineNumber, ThisClassName, ParentClassNameTypedef , RTTREnable,
                              mCurrentFileID, mReflDeclLineNumber));
    // clang-format on
    os << RegisterGeneratedBody << "\n";
}

std::map<std::string, std::string> ClassEntity::GetFieldAttributes(
    const std::string& AttrStr) const {
    std::map<std::string, std::string> AttrMap;
    std::string                        AttrStrCopy = AttrStr;
    // 按","分割字符串
    std::vector<std::string> Attrs;
    while (!AttrStrCopy.empty()) {
        auto Pos = AttrStrCopy.find(',');
        if (Pos == std::string::npos) {
            Attrs.push_back(AttrStrCopy);
            break;
        }
        Attrs.push_back(AttrStrCopy.substr(0, Pos));
        AttrStrCopy = AttrStrCopy.substr(Pos + 1);
    }
    for (const auto& Attr: Attrs) {
        auto Pos = Attr.find('=');
        if (Pos == std::string::npos) {
            // 去除Attr周围的空格
            std::string TrimmedAttrStr = Trim(Attr);
            if (IsSpace(TrimmedAttrStr)) continue;
            AttrMap[TrimmedAttrStr] = "True";
        } else {
            std::string Key        = Attr.substr(0, Pos);
            std::string TrimmedKey = Trim(Trim(Trim(Key, " "), "\""), "\"");
            if (IsSpace(TrimmedKey)) continue;

            std::string Value        = Attr.substr(Pos + 1);
            std::string TrimmedValue = Trim(Trim(Trim(Value, " "), "\""), "\"");
            if (IsSpace(TrimmedValue)) continue;

            AttrMap[TrimmedKey] = TrimmedValue;
        }
    }
    return AttrMap;
}
