/**
 * @file ReflectedEntityFinder.cpp
 * @author Echo 
 * @Date 24-4-5
 * @brief 
 */

#include "ReflectedEntityFinder.h"
#include <filesystem>
#include <iostream>
using namespace std::string_literals;

// 去掉字符串两端的空格
std::string Trim(const std::string& Str, const std::string& TrimStr = " ") {
    if (Str.empty()) {
        return Str;
    }
    std::string S = Str;
    if (S.find_first_not_of(TrimStr) != std::string::npos) {
        S.erase(0, S.find_first_not_of(TrimStr));
    }
    if (S.find_last_not_of(TrimStr) != std::string::npos) {
        S.erase(S.find_last_not_of(TrimStr) + 1);
    }
    return S;
}

bool ReplaceOne(std::string& str, const std::string& from, const std::string& to) {
    size_t start_pos = str.find(from);
    if (start_pos == std::string::npos) return false;
    str.replace(start_pos, from.length(), to);
    return true;
}

bool IsSpace(std::string Str) {
    return std::ranges::all_of(Str, [](char c) { return std::isspace(c); });
}

void ReplaceAll(std::string& str, const std::string& from, const std::string& to) {
    if (from.empty()) return;
    size_t start_pos = 0;
    while ((start_pos = str.find(from, start_pos)) != std::string::npos) {
        str.replace(start_pos, from.length(), to);
        start_pos += to.length();   // In case 'to' contains 'from', like replacing 'x' with 'yx'
    }
}

void ReflectedEntityFinder::run(const clang::ast_matchers::MatchFinder::MatchResult& Result) {
    using namespace clang;
    mContext       = Result.Context;
    mSourceManager = Result.SourceManager;

    if (const auto Record = Result.Nodes.getNodeAs<CXXRecordDecl>("class"))
        return FoundRecord(Record);
    if (const auto Field = Result.Nodes.getNodeAs<FieldDecl>("field")) return FoundField(Field);
    if (const auto Enum = Result.Nodes.getNodeAs<EnumDecl>("enum")) return FoundEnum(Enum);
    if (const auto EnumConstant = Result.Nodes.getNodeAs<EnumConstantDecl>("enum_constant"))
        return FoundEnumConstant(EnumConstant);
}

void ReflectedEntityFinder::FoundField(const clang::FieldDecl* Decl) {
    if (mRecordEntities.empty()) return;
    mRecordEntities.back().AddField(Decl);
}

void ReflectedEntityFinder::FoundEnum(const clang::EnumDecl* Decl) {
    mOriginalFilename = mSourceManager->getFilename(Decl->getLocation()).str();
    // 获取文件名字
    if (mFileID.empty()) {
        const std::filesystem::path FilePath = mOriginalFilename;
        std::string FileID                   = FilePath.filename().generic_string();
        ReplaceOne(FileID, ".", "_");
        mFileID = FileID;
    }
    // 看看Enum有没有Reflected属性
    for (auto& Attr: Decl->attrs()) {
        if (Attr->getKind() == clang::attr::Annotate) {
            if (const auto* AnnotateAttr = static_cast<clang::AnnotateAttr*>(Attr);
                AnnotateAttr->getAnnotation().starts_with("Reflected")) {
                mEnumEntites.emplace_back(Decl, mFileID);
                break;
            }
        }
    }
}

void ReflectedEntityFinder::FoundEnumConstant(const clang::EnumConstantDecl* Decl) {
    if (mEnumEntites.empty()) return;
    mEnumEntites.back().AddConstant(Decl);
}

void ReflectedEntityFinder::FoundRecord(const clang::CXXRecordDecl* Decl) {
    mOriginalFilename = mSourceManager->getFilename(Decl->getLocation()).str();
    // 获取文件名字
    if (mFileID.empty()) {
        const std::filesystem::path FilePath = mOriginalFilename;
        std::string FileID                   = FilePath.filename().generic_string();
        ReplaceOne(FileID, ".", "_");
        mFileID = FileID;
    }
    // 看看这个类有没有Reflected属性
    for (auto& Attr: Decl->attrs()) {
        if (Attr->getKind() == clang::attr::Annotate) {
            if (const auto* AnnotateAttr = static_cast<clang::AnnotateAttr*>(Attr);
                AnnotateAttr->getAnnotation().starts_with("Reflected")) {
                mRecordEntities.emplace_back(Decl, mConfig, mFileID);
                break;
            }
        }
    }
    if (mOriginalFilename.ends_with(".generated.h")) {
        llvm::outs() << "Skip generated file: " << mOriginalFilename << "\n";
        exit(0);
    }
    if (!mOriginalFilename.empty() && !mGeneratedFilename.empty()) return;
    mGeneratedFilename = mOriginalFilename;
    mGeneratedFilename.replace(mGeneratedFilename.find(".h"), 2, ".generated.h");
}

void ReflectedEntityFinder::onEndOfTranslationUnit() {
    MatchCallback::onEndOfTranslationUnit();
    if (mEnumEntites.empty() && mRecordEntities.empty()) return;
    std::error_code ec;
    std::filesystem::path Path = mGeneratedFilename;
    Path                       = std::filesystem::path(mOutputPath) / Path.filename();
    mGeneratedFilename         = Path.string();
    llvm::raw_fd_ostream os(mGeneratedFilename, ec);
    assert(!ec && "error opening file");
    std::cout << "Generated file: " << mGeneratedFilename << "\n";
    os << "// This file generated by generator, do not edit it.\n";
    os << "#ifndef GENERATED_CODE_" << mFileID << "\n";
    os << "#define GENERATED_CODE_" << mFileID << "\n";
    std::vector<std::string> MacroStrs;
    for (auto& Ref: mRecordEntities) {
        MacroStrs.push_back(Ref.Generate(mContext, os));
    }
    for (auto& Ref: mEnumEntites) {
        MacroStrs.push_back(Ref.Generate(mContext, os));
    }
    os << "#define GENERATED_SOURCE_" << mFileID << " \\\n";
    for (const auto& MacroStr: MacroStrs) {
        os << MacroStr << " \\\n";
    }
    os << ";\n";
    os << "#undef CURRENT_FILE_ID\n";
    os << "#define CURRENT_FILE_ID " << mFileID << "\n";
    os << "#endif";
    os.close();
}

std::string ClassEntity::GetBaseClassName() const {
    if (!mRecord->bases().empty()) {
        const clang::CXXBaseSpecifier* BaseSpecifier = mRecord->bases_begin();
        const CXXRecordDecl* BaseRecordDecl = BaseSpecifier->getType()->getAsCXXRecordDecl();
        const std::string base_class_name   = BaseRecordDecl->getQualifiedNameAsString();
        return base_class_name;
    }
    return "";
}

std::string ClassEntity::GetClassQualifiedName() const {
    if (mRecord) {
        return mRecord->getQualifiedNameAsString();
    }
    return "";
}
std::string ClassEntity::GetClassName() const {
    if (mRecord) {
        return mRecord->getNameAsString();
    }
    return "";
}

void ClassEntity::GenerateField(
    const clang::FieldDecl* Decl, const std::map<std::string, std::string>& AttrMap,
    llvm::raw_fd_ostream& os
) const {
    if (!AttrMap.contains("Reflected") || AttrMap.at("Reflected") != "True") return;
    std::string FieldDeclName       = Decl->getNameAsString();
    std::string FieldName           = FieldDeclName;
    auto QualifiedClassName         = GetClassQualifiedName();
    const std::string FieldTypeName = Decl->getType().getAsString();
    if (AttrMap.contains("Name")) {
        FieldName = AttrMap.at("Name");
    }
    std::string RegisterStr = std::vformat(
        R"(.property("{}", &{}::{}))",
        std::make_format_args(FieldName, QualifiedClassName, FieldDeclName)
    );
    for (const auto& [Key, Value]: AttrMap) {
        if (Key == "Name") continue;
        if (Key == "Reflected") continue;
        RegisterStr +=
            std::vformat(R"((rttr::metadata("{}", "{}")))", std::make_format_args(Key, Value));
    }
    if (mConig.isMember("RefWrapperType")) {
        for (auto& Value: mConig["RefWrapperType"]) {
            auto WarpperStr = Value.asString();
            if (FieldTypeName.starts_with(WarpperStr)) {
                RegisterStr += std::string("(rttr::policy::prop::as_reference_wrapper)");
                break;
            }
        }
    }
    RegisterStr += " \\\n";
    os << RegisterStr;
}

std::string EnumEntity::Generate(const clang::ASTContext* Context, llvm::raw_fd_ostream& OS) const {
    std::string CodeBody;
    CodeBody += "(";
    auto UnderlineEnumName = GetEnumUnderlineName();
    auto QualifiedEnumName = GetQualifiedEnumName();
    auto EnumName          = mEnumDecl->getNameAsString();
    std::cout << EnumName;
    for (const auto* ConstantDecl: mConstants) {
        auto ConstantDeclName = ConstantDecl->getNameAsString();
        CodeBody += std::vformat(
            R"(rttr::value("{}", {}::{}), )",
            std::make_format_args(ConstantDeclName, QualifiedEnumName, ConstantDeclName)
        );
    }
    // 删除最后一个","
    CodeBody.erase(CodeBody.find_last_of(','));
    CodeBody += ")";
    auto EnumMacroString = std::vformat(
        "GENERATED_ENUM_CODE_{}_{}", std::make_format_args(mCurrentFileID, UnderlineEnumName)
    );
    const std::string EnumBody = std::vformat(
        R"(
#define {} \
    rttr::registration::enumeration<{}>("{}") \
    {};
)",
        std::make_format_args(
            EnumMacroString, QualifiedEnumName, UnderlineEnumName, CodeBody
        )
    );
    OS << EnumBody;
    return EnumMacroString;
}

std::string EnumEntity::GetQualifiedEnumName() const {
    return mEnumDecl->getQualifiedNameAsString();
}

std::string EnumEntity::GetEnumUnderlineName() const {
    auto Name = GetQualifiedEnumName();
    ReplaceAll(Name, "::", "_");
    return Name;
}

std::string
ClassEntity::Generate(const clang::ASTContext* context, llvm::raw_fd_ostream& os) const {
    auto ClassName = GetClassName();
    auto CodeMacroStr =
        std::vformat(R"(GENERATED_CODE_{}{})", std::make_format_args(mCurrentFileID, ClassName));
    const std::string CodeDefineMacroStr =
        std::vformat(R"(#define {} \)", std::make_format_args(CodeMacroStr));
    auto ClassQualifiedName = GetClassQualifiedName();
    os << CodeDefineMacroStr << "\n";

    const std::string RegisterClassCode = std::vformat(
        R"(rttr::registration::class_<{}>("{}").constructor<>()(rttr::policy::ctor::as_object) \)",
        std::make_format_args(ClassQualifiedName, ClassQualifiedName)
    );
    os << RegisterClassCode << "\n";
    for (const auto& Field: mFields) {
        // 寻找annoation attr
        std::string AttrStr;
        for (const auto& attr: Field->attrs()) {
            if (attr->getKind() == clang::attr::Annotate) {
                const auto* AnnotateAttr = static_cast<clang::AnnotateAttr*>(attr);
                AttrStr                  = AnnotateAttr->getAnnotation();
                break;
            }
        }
        auto AttrMap = GetFieldAttributes(AttrStr);
        GenerateField(Field, AttrMap, os);
    }
    os << ";\n";
    std::string ThisClassName         = GetClassQualifiedName();
    const std::string ParentClassName = GetBaseClassName();
    std::string ParentClassNameTypedef =
        ParentClassName.empty() ? "" : "typedef "s + ParentClassName + " Super;";
    std::string RTTREnable = ParentClassName.empty() ? "" : "RTTR_ENABLE("s + ParentClassName + ")";
    // clang-format off
    const std::string RegisterGeneratedBody = std::vformat(R"(
#define GENERATED_BODY_{}_{} \
public: \
    typedef {} ThisClass; \
    {} \
    {} \
    RTTR_REGISTRATION_FRIEND \
private:
)",std::make_format_args(mCurrentFileID, ClassName, ThisClassName, ParentClassNameTypedef , RTTREnable));
    // clang-format on
    os << RegisterGeneratedBody << "\n";
    return CodeMacroStr;
}

std::map<std::string, std::string> ClassEntity::GetFieldAttributes(const std::string& AttrStr
) const {
    std::map<std::string, std::string> AttrMap;
    std::string AttrStrCopy = AttrStr;
    // 按","分割字符串
    std::vector<std::string> Attrs;
    while (!AttrStrCopy.empty()) {
        auto Pos = AttrStrCopy.find(',');
        if (Pos == std::string::npos) {
            Attrs.push_back(AttrStrCopy);
            break;
        }
        Attrs.push_back(AttrStrCopy.substr(0, Pos));
        AttrStrCopy = AttrStrCopy.substr(Pos + 1);
    }
    for (const auto& Attr: Attrs) {
        auto Pos = Attr.find('=');
        if (Pos == std::string::npos) {
            // 去除Attr周围的空格
            std::string TrimmedAttrStr = Trim(Attr);
            if (IsSpace(TrimmedAttrStr)) continue;
            AttrMap[TrimmedAttrStr] = "True";
        } else {
            std::string Key        = Attr.substr(0, Pos);
            std::string TrimmedKey = Trim(Trim(Trim(Key, " "), "\""), "\"");
            if (IsSpace(TrimmedKey)) continue;

            std::string Value        = Attr.substr(Pos + 1);
            std::string TrimmedValue = Trim(Trim(Trim(Value, " "), "\""), "\"");
            if (IsSpace(TrimmedValue)) continue;

            AttrMap[TrimmedKey] = TrimmedValue;
        }
    }
    return AttrMap;
}
