// this file is generated by code generator, do not modify
#ifdef TEST_GENERATED_H
#error "generated file for Test.h has been included!"
#endif
#ifndef TEST_GENERATED_H
#define TEST_GENERATED_H

#define GENERATED_CODE_24 \
{\
rttr::registration::class_<A>("A")\
    .property("d", &A::d)(rttr::metadata("K", "True"))\
    .property("APC", &A::ABC)(rttr::metadata("Serialized", "True"))\
;\
}

#define GENERATED_BODY_INTERNAL_Test_h_24 \
public:\
    typedef Object Super;\
    typedef A ThisClass;\
    RTTR_ENABLE(Object)\
    RTTR_REGISTRATION_IN_CLASS(A)\
    GENERATED_CODE_24

#define GENERATED_CODE_34 \
{\
rttr::registration::class_<C>("C")\
    .property("d", &C::d)(rttr::metadata("K", "True"))\
    .property("APC", &C::ABC)(rttr::metadata("Serialized", "True"))\
;\
}

#define GENERATED_BODY_INTERNAL_Test_h_34 \
public:\
    typedef Object Super;\
    typedef C ThisClass;\
    RTTR_ENABLE(Object)\
    RTTR_REGISTRATION_IN_CLASS(C)\
    GENERATED_CODE_34
#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Test_h
#endif
