// This file generated by generator, do not edit it.
#ifndef GENERATED_CODE_Test_h
#define GENERATED_CODE_Test_h
#define GENERATED_CODE_Test_hT2 \
rttr::registration::class_<T2>("T2") \
.property("c", &T2::c) \
;

#define GENERATED_BODY_Test_h_T2 \
public: \
    typedef T2 ThisClass; \
    typedef Object Super; \
    RTTR_ENABLE(Object) \
    RTTR_REGISTRATION_FRIEND \
    REGISTRATION_IN_CLASS(CURRENT_FILE_ID, __LINE__) { \
        GENERATED_CODE_Test_hT2 \
    } \
private:
#define GENERATED_CODE_Test_hT1 \
rttr::registration::class_<T1>("T1") \
;

#define GENERATED_BODY_Test_h_T1 \
public: \
    typedef T1 ThisClass; \
    typedef Object Super; \
    RTTR_ENABLE(Object) \
    RTTR_REGISTRATION_FRIEND \
    REGISTRATION_IN_CLASS(CURRENT_FILE_ID, __LINE__) { \
        GENERATED_CODE_Test_hT1 \
    } \
private:
#define GENERATED_CODE_Test_hTestReflection \
rttr::registration::class_<Test::TestReflection>("Test::TestReflection") \
.property("K", &Test::TestReflection::i32)(rttr::metadata("Serialized", "True")) \
.property("K1", &Test::TestReflection::i64)(rttr::metadata("Serialized", "True")) \
.property("CharArray", &Test::TestReflection::CharArray) \
;

#define GENERATED_BODY_Test_h_TestReflection \
public: \
    typedef Test::TestReflection ThisClass; \
    typedef Object Super; \
    RTTR_ENABLE(Object) \
    RTTR_REGISTRATION_FRIEND \
    REGISTRATION_IN_CLASS(CURRENT_FILE_ID, __LINE__) { \
        GENERATED_CODE_Test_hTestReflection \
    } \
private:

#define GENERATED_ENUM_CODE_Test_h_TestEnum1 \
    rttr::registration::enumeration<TestEnum1>("TestEnum1") \
    (rttr::value("A", TestEnum1::A), rttr::value("PV", TestEnum1::PV));

#define GENERATED_ENUM_CODE_Test_h_TestEnum \
    rttr::registration::enumeration<TestEnum>("TestEnum") \
    (rttr::value("A", TestEnum::A), rttr::value("B", TestEnum::B), rttr::value("C", TestEnum::C));

#define GENERATED_ENUM_CODE_Test_h_TestEnumc \
    rttr::registration::enumeration<TestEnumc>("TestEnumc") \
    (rttr::value("A", TestEnumc::A), rttr::value("B", TestEnumc::B), rttr::value("C", TestEnumc::C));
#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Test_h
#endif